import { currentDateKey } from "../domain/model.js";
import type { StudyPlan } from "../domain/model.js";
import type {
  AiPlanComposerDraft,
  AppInfoItem,
  BatchPlanDraft,
  HabitCheckInDraft,
  HabitFilterOption,
  HabitDraft,
  HabitStatsRangeOption,
  HelpFeatureCard,
  MoreFeatureSection,
  PlanDraft,
  QuickCompleteDraft,
  WishDraft,
} from "./app-types.js";

// Static UI content is isolated here so product-copy changes do not require opening the app shell.
export function createInitialPlanDraft(dateKey: string = currentDateKey()): PlanDraft {
  return {
    startDate: dateKey,
    category: "",
    title: "",
    content: "",
    repeatType: "once",
    timeMode: "duration",
    durationMinutes: "25",
    startTime: "19:00",
    endTime: "20:30",
    useCustomPoints: false,
    customPoints: "3",
    attachments: [],
  };
}

export function createPlanDraftFromPlan(plan: StudyPlan): PlanDraft {
  const estimatedStars = Math.max(1, Math.round(plan.minutes / 10));
  return {
    startDate: plan.createdAt.slice(0, 10),
    category: plan.subject,
    title: plan.title,
    content: "",
    repeatType: plan.repeatType,
    timeMode: "duration",
    durationMinutes: String(plan.minutes),
    startTime: plan.createdAt.slice(11, 16) || "08:00",
    endTime: "20:30",
    useCustomPoints: plan.stars !== estimatedStars,
    customPoints: String(plan.stars),
    attachments: [],
  };
}

export function createInitialBatchPlanDraft(dateKey: string = currentDateKey()): BatchPlanDraft {
  return {
    rawText: "",
    startDate: dateKey,
    repeatType: "once",
    defaultDurationMinutes: "25",
    useCustomPoints: false,
    customPoints: "10",
    approvalRequired: false,
  };
}

export function createInitialWishDraft(): WishDraft {
  return {
    iconCategory: "toy",
    icon: "🧸",
    customImage: null,
    customImageName: "",
    title: "",
    description: "",
    category: "toy",
    cost: "10",
    repeatMode: "single",
    maxRedemptions: "5",
    resetPeriod: "weekly",
    redemptionsPerPeriod: "1",
  };
}

export const INITIAL_AI_PLAN_COMPOSER_DRAFT: AiPlanComposerDraft = {
  prompt: "",
  attachments: [],
};

export const AI_PLAN_PROMPT_EXAMPLES = ["每天晚上7点学习数学", "每2天游泳一次", "周末运动1小时"];

export const PLAN_DURATION_PRESETS = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 75, 90, 120, 150, 180];
export const INITIAL_QUICK_COMPLETE_DRAFT: QuickCompleteDraft = {
  planId: "",
  mode: "duration",
  hours: "0",
  minutes: "0",
  seconds: "0",
  note: "",
  attachments: [],
};
export const INITIAL_HABIT_DRAFT: HabitDraft = {
  name: "",
  description: "",
  frequency: "dailyOnce",
  points: "1",
  approvalRequired: false,
  icon: "☆",
  color: "#4f7cff",
};
export const INITIAL_HABIT_CHECKIN_DRAFT: HabitCheckInDraft = {
  habitId: "",
  note: "",
  useCustomPoints: false,
  customPoints: "0",
};
export const SUBJECT_OPTIONS = [
  "语文",
  "数学",
  "英语",
  "物理",
  "化学",
  "生物",
  "历史",
  "地理",
  "政治",
  "道德与法治",
  "信息技术",
  "运动",
  "娱乐",
  "技能",
];
export const WEEKDAY_LABELS = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"];
export const HABIT_ICONS = ["☆", "◎", "○", "◇", "△", "□", "⌚", "☀", "☾", "♫", "✎", "☕", "⌂", "⚑", "⚡", "☘", "✓", "✿", "♞", "☂", "♻", "♡", "♢", "☼"];
export const HABIT_COLORS = ["#4f7cff", "#8a83ff", "#55c5df", "#63d0bf", "#57c884", "#9bd24f", "#ffcf56", "#ff9d5c", "#f47a7a", "#f36c90", "#df6dba", "#ad72f2"];
export const HABIT_FILTER_OPTIONS: HabitFilterOption[] = [
  { value: "all", label: "全部" },
  { value: "positive", label: "加分" },
  { value: "negative", label: "扣分" },
  { value: "completed", label: "已完成" },
  { value: "pending", label: "待完成" },
  { value: "dailyMultiple", label: "每日多次" },
  { value: "weeklyMultiple", label: "每周多次" },
];

export const HABIT_STATS_RANGE_OPTIONS: HabitStatsRangeOption[] = [
  { value: "week", label: "本周" },
  { value: "month", label: "本月" },
  { value: "history", label: "历史记录" },
];

export const QUICK_COMPLETE_PRESETS = [
  { label: "15分钟", seconds: 15 * 60 },
  { label: "30分钟", seconds: 30 * 60 },
  { label: "45分钟", seconds: 45 * 60 },
  { label: "1小时", seconds: 60 * 60 },
  { label: "1.5小时", seconds: 90 * 60 },
  { label: "2小时", seconds: 120 * 60 },
];

export const HELP_QUICK_START_STEPS = [
  "先添加 3~5 个核心学习计划（每天可执行）。",
  "用待办归类零碎任务，再转成正式计划。",
  "连续打卡 7 天后，看图表统计做一次复盘。",
  "录入考试成绩，再用成绩分析生成专项提升计划。",
];

export const HELP_PLAN_FIELD_LINES = [
  "必填：计划名称、重复类型、目标日期/起始日期。",
  "可填：类别、计划内容、时间模式、附件、积分与家审定设置。",
  "重复类型解释：",
  "仅当天：只在目标日期创建 1 次任务，适合临时安排。",
  "每天：从起始日期开始每天生成任务，适合日常固定动作。",
  "每周：按勾选的周几重复（如周一/周三/周五）。",
  "每双周：按双周节奏重复，适合同周期任务。",
  "文案进阶：按记忆曲线生成先放习再背，适合背诵/记忆类内容。",
  "本周一次：跨日任务，在当前周期内完成后计次。",
  "每周一次/每月一次：跨日任务，每个周期至少完成设定次数。",
];

export const HELP_FEATURE_CARDS: HelpFeatureCard[] = [
  {
    id: "study-plans",
    title: "学习计划（手动 / 智能 / 批量）",
    icon: "📘",
    accent: "#2f6dff",
    action: "plans",
    howTo: [
      "先用“添加计划”建核心任务：名称、重复类型、日期是重点。",
      "需要同类任务时用“批量添加”，按类别与任务格式粘贴。",
      "需求不规则时用“智能创建”，先生成草稿再确认。",
    ],
    tips: [
      "计划名称建议写成“动作 + 对象 + 时长/数量”。",
      "跨日任务建议设置完成节点，避免和其他任务冲突。",
    ],
  },
  {
    id: "todos",
    title: "待办事项（转计划）",
    icon: "☑️",
    accent: "#5a6cff",
    action: "help-placeholder",
    howTo: [
      "先把零散想法记录待办（内容 + 备注）。",
      "点击“转为计划”，系统会自动预填计划表单。",
      "校对后保存，待办会自动标记为“已关联计划”。",
    ],
    tips: ["适合把临时灵感转成可执行计划，减少遗漏。"],
  },
  {
    id: "score-tracking",
    title: "成绩追踪 + 成绩分析",
    icon: "🧪",
    accent: "#25b874",
    action: "help-placeholder",
    howTo: [
      "先在成绩追踪录入考试记录（科目、分数、日期、满分）。",
      "再进成绩分析查看弱项、题型分布和趋势。",
      "从分析结果创建专项练习计划，形成闭环提升。",
    ],
    tips: ["同学科建议至少录入 3 次考试，分析结果更稳定。"],
  },
  {
    id: "charts",
    title: "图表统计（复盘）",
    icon: "📊",
    accent: "#b35cff",
    action: "habit-stats",
    howTo: [
      "看完成率：判断执行稳定性。",
      "看时长与分类占比：判断是否偏科、投入是否均衡。",
      "看趋势线：重点关注 7 天/30 天变化。",
    ],
    tips: ["建议固定每周复盘一次，并据此调整下周计划配比。"],
  },
  {
    id: "habits",
    title: "行为习惯",
    icon: "💗",
    accent: "#ff6285",
    action: "habits",
    howTo: [
      "在“习惯管理”创建习惯（如晨读、运动、早睡）。",
      "每日打卡，持续积累星星积分。",
      "在习惯统计页查看连续天数与完成率。",
    ],
    tips: ["先从 1~2 个习惯开始，不建议一次建太多。"],
  },
  {
    id: "listening",
    title: "听写背诵",
    icon: "🎙️",
    accent: "#36b9d6",
    action: "help-placeholder",
    howTo: [
      "输入文本后先分段（按行/空格/智能分段）。",
      "设置播放顺序、重复次数、间隔，再开始听写。",
      "切换背诵模式做空缺练习，最后看历史记录。",
    ],
    tips: ["先用短文本调好参数，再练长文本，体验更好。"],
  },
  {
    id: "printing",
    title: "任务打印",
    icon: "🖨️",
    accent: "#3f5068",
    action: "help-placeholder",
    howTo: [
      "选择打印范围（按日/按周）。",
      "确认包含模块和格式后导出。",
      "打印前先预览，避免日期或项目遗漏。",
    ],
    tips: ["建议在周日统一打印下周任务清单。"],
  },
  {
    id: "body",
    title: "身高管理",
    icon: "📏",
    accent: "#2ec6c0",
    action: "help-placeholder",
    howTo: [
      "在档案页完善基础信息。",
      "定期记录身高体重与相关习惯。",
      "在报告页查看趋势和阶段变化。",
    ],
    tips: ["固定同一时间测量，数据可比性更强。"],
  },
  {
    id: "savings",
    title: "存钱罐 + 兴趣班记录",
    icon: "⭐",
    accent: "#ff9d2f",
    action: "help-placeholder",
    howTo: [
      "存钱罐记录每次存取，关注余额与流水。",
      "兴趣班记录课程、课时消耗和上课明细。",
      "定期复盘投入和产出，帮助家长决策。",
    ],
    tips: ["建议每月做一次汇总，便于长期对比。"],
  },
  {
    id: "reading",
    title: "我的阅读",
    icon: "📖",
    accent: "#4f7cff",
    action: "reading-journey",
    howTo: [
      "先在书架里添加书籍，补充分类、总页数等基础信息。",
      "每次阅读后记录日期、页码范围、时长和心得。",
      "去统计页看阅读趋势、分类分布和累计数据。",
    ],
    tips: ["拍照识别后先校对书名，第一期先支持手动录入与统计。"],
  },
  {
    id: "timer",
    title: "337 晨读 + 专注计时器",
    icon: "⏱️",
    accent: "#8b5cff",
    action: "help-placeholder",
    howTo: [
      "337 晨读：先建计划，再按每日任务打卡。",
      "计时器：按场景选择正计时/倒计时/番茄钟。",
      "把计时器与计划任务结合，提升执行专注度。",
    ],
    tips: ["建议设置固定学习时段，形成稳定节奏。"],
  },
  {
    id: "classroom",
    title: "老师/学生班级协作",
    icon: "🎓",
    accent: "#df54d2",
    action: "help-placeholder",
    howTo: [
      "老师端：创建班级、发布学习计划、查看完成进度。",
      "学生端：加入班级、接收任务、跟进作业完成。",
      "按周看到班级整体完成情况并及时调整。",
    ],
    tips: ["老师发布任务时建议统一命名规范，便于统计。"],
  },
];

export const MORE_FEATURE_SECTIONS: MoreFeatureSection[] = [
  {
    id: "membership",
    title: "会员功能",
    icon: "👑",
    accent: "#ff8a1f",
    columns: 2,
    cards: [
      {
        id: "membership-management",
        title: "会员管理",
        description: "查看会员状态和权限",
        icon: "👑",
        accent: "#ff8a1f",
        action: "placeholder",
        featured: true,
        keywords: ["会员", "权限", "升级", "高级版"],
        message: "会员管理页面我已经预留入口，后续按截图继续补会员状态和权限细节。",
      },
      {
        id: "redeem-code",
        title: "兑换码",
        description: "输入兑换码升级会员",
        icon: "🎁",
        accent: "#bf46f1",
        action: "placeholder",
        keywords: ["兑换码", "会员", "激活码"],
        message: "兑换码流程还没有单独截图，我先保留成可搜索入口，后续继续接。",
      },
    ],
  },
  {
    id: "general",
    title: "通用功能",
    icon: "⚙️",
    accent: "#537ecf",
    columns: 3,
    cards: [
      {
        id: "habits",
        title: "行为习惯",
        description: "打卡培养好习惯，赚取星星积分",
        icon: "❤️",
        accent: "#ff4d7a",
        action: "habit-management",
        keywords: ["习惯", "打卡", "行为"],
      },
      {
        id: "reading",
        title: "我的阅读",
        description: "管理书架、记录阅读、查看阅读统计",
        icon: "📘",
        accent: "#4f7cff",
        action: "reading-journey",
        keywords: ["阅读", "书架", "书籍", "读书"],
        badge: "新功能",
      },
      {
        id: "morning-reading",
        title: "337晨读",
        description: "科学高效的阅读学习方法",
        icon: "📖",
        accent: "#4f7cff",
        action: "placeholder",
        keywords: ["337", "晨读", "阅读"],
        badge: "新功能",
        message: "337 晨读页面还没开始实现，等你给截图后我可以继续接。",
      },
      {
        id: "listening",
        title: "听写背诵",
        description: "听写练习与背诵巩固",
        icon: "🎙️",
        accent: "#1f9ef4",
        action: "placeholder",
        keywords: ["听写", "背诵", "默写", "语音"],
        message: "听写背诵工作区还没有实现，当前先保留入口说明。",
      },
      {
        id: "timer",
        title: "专注计时器",
        description: "正计时、倒计时、番茄钟一体",
        icon: "⏱️",
        accent: "#8f54f8",
        action: "placeholder",
        keywords: ["计时器", "专注", "番茄钟", "倒计时"],
        badge: "新功能",
        message: "专注计时器已有规格但还没编码完成，我先把入口放进其他功能页。",
      },
      {
        id: "pet",
        title: "电子宠物",
        description: "领养小伙伴，在星星陪伴下一起成长",
        icon: "🐾",
        accent: "#ff6c3f",
        action: "pet-center",
        keywords: ["宠物", "电子宠物", "陪伴", "星星"],
        badge: "新功能",
      },
      {
        id: "plan-selection",
        title: "计划精选",
        description: "浏览和使用优质学习计划",
        icon: "✨",
        accent: "#ff971f",
        action: "placeholder",
        keywords: ["计划", "精选", "学习计划"],
        badge: "新功能",
        message: "计划精选页还没有下游截图，当前先保留入口。",
      },
      {
        id: "score-tracking",
        title: "成绩追踪",
        description: "记录考试成绩，跟踪学习进步",
        icon: "📊",
        accent: "#7a59ff",
        action: "placeholder",
        keywords: ["成绩", "追踪", "考试", "分数"],
        badge: "新功能",
        message: "成绩追踪模块还没开始实现，后续按截图补录入和历史列表。",
      },
      {
        id: "score-analysis",
        title: "成绩分析",
        description: "薄弱知识点分析与专项练习",
        icon: "🧩",
        accent: "#20ba88",
        action: "placeholder",
        keywords: ["成绩分析", "薄弱项", "考试", "知识点"],
        badge: "新功能",
        message: "成绩分析页面还没有单独编码，等你继续发截图我会接进去。",
      },
      {
        id: "printing",
        title: "任务打印",
        description: "打印每日或每周学习任务清单",
        icon: "🖨️",
        accent: "#2795eb",
        action: "placeholder",
        keywords: ["打印", "任务", "清单"],
        badge: "新功能",
        message: "任务打印还没有实现导出/打印排版，目前先保留入口。",
      },
      {
        id: "todos",
        title: "待办事项",
        description: "记录待办并一键创建学习计划",
        icon: "☑️",
        accent: "#7d57f4",
        action: "placeholder",
        keywords: ["待办", "事项", "转计划"],
        badge: "新功能",
        message: "待办事项模块还没编码完成，但现在已经能在帮助页和其他功能页里找到入口。",
      },
    ],
  },
  {
    id: "system",
    title: "系统功能",
    icon: "⚙",
    accent: "#667085",
    columns: 3,
    cards: [
      {
        id: "child-mode",
        title: "儿童模式设置",
        description: "家长控制，限制孩子访问管理功能",
        icon: "🧒",
        accent: "#f59e0b",
        action: "placeholder",
        keywords: ["儿童模式", "家长控制", "限制"],
        badge: "新功能",
        message: "儿童模式设置还没有具体页面截图，我先保留系统入口。",
      },
      {
        id: "account-security",
        title: "账号密码修改",
        description: "修改登录账号与密码",
        icon: "🔑",
        accent: "#19b392",
        action: "placeholder",
        keywords: ["账号", "密码", "安全"],
        badge: "新功能",
        message: "账号密码修改属于后续系统模块，当前先放导航占位。",
      },
      {
        id: "user-management",
        title: "用户管理",
        description: "管理用户账户和权限",
        icon: "👥",
        accent: "#9b53f6",
        action: "placeholder",
        keywords: ["用户", "管理", "权限"],
        message: "用户管理还没有独立截图和下游表单，当前只保留入口。",
      },
      {
        id: "dashboard-config",
        title: "仪表盘配置",
        description: "自定义仪表盘模块显示和排序",
        icon: "◫",
        accent: "#4f7cff",
        action: "placeholder",
        keywords: ["仪表盘", "配置", "排序"],
        badge: "新功能",
        message: "仪表盘配置涉及首页模块排序，后续拿到截图后再实现。",
      },
      {
        id: "system-settings",
        title: "系统设置",
        description: "管理奖励样式和应用偏好",
        icon: "⚙️",
        accent: "#6b7280",
        action: "placeholder",
        keywords: ["系统设置", "偏好", "配置"],
        message: "系统设置页还没开始实现，暂时先留入口。",
      },
      {
        id: "data-export",
        title: "数据导出",
        description: "导出学习数据和统计信息",
        icon: "⬇️",
        accent: "#22c55e",
        action: "placeholder",
        keywords: ["导出", "备份", "数据"],
        message: "数据导出当前仍在里程碑外，入口已经预留。",
      },
      {
        id: "data-import",
        title: "数据导入",
        description: "从备份文件恢复学习数据",
        icon: "⬆️",
        accent: "#6366f1",
        action: "placeholder",
        keywords: ["导入", "恢复", "备份"],
        message: "数据导入当前仍在里程碑外，入口先保留说明。",
      },
      {
        id: "help",
        title: "使用帮助",
        description: "查看使用指南和常见问题",
        icon: "❓",
        accent: "#f97316",
        action: "help-center",
        keywords: ["帮助", "说明", "指南"],
        badge: "新功能",
      },
    ],
  },
  {
    id: "school",
    title: "学校与机构",
    icon: "🏫",
    accent: "#8759ff",
    columns: 2,
    cards: [
      {
        id: "teacher-classroom",
        title: "班级管理（老师）",
        description: "创建班级，发布学习计划",
        icon: "🏫",
        accent: "#8759ff",
        action: "placeholder",
        keywords: ["班级", "老师", "学校"],
        badge: "新功能",
        message: "老师端班级管理还没开始实现，等你给到截图后我会接。",
      },
      {
        id: "student-classroom",
        title: "我的班级（学生）",
        description: "查看加入的班级和作业",
        icon: "🧑‍🏫",
        accent: "#ff6a21",
        action: "placeholder",
        keywords: ["班级", "学生", "作业"],
        badge: "新功能",
        message: "学生端班级页面还没实现，当前先保留入口。",
      },
    ],
  },
  {
    id: "others",
    title: "其他功能",
    icon: "📎",
    accent: "#19b392",
    columns: 3,
    cards: [
      {
        id: "body",
        title: "身高管理",
        description: "记录身高体重，追踪生长趋势",
        icon: "📏",
        accent: "#19b392",
        action: "placeholder",
        keywords: ["身高", "体重", "成长"],
        badge: "新功能",
        message: "身高管理页面还没单独实现，目前先保留在其他功能页。",
      },
      {
        id: "savings",
        title: "存钱罐",
        description: "记录存取，查看余额与流水",
        icon: "🐷",
        accent: "#ff8a1f",
        action: "placeholder",
        keywords: ["存钱罐", "余额", "流水", "存钱"],
        badge: "新功能",
        message: "存钱罐模块还没有截图和数据规则，我先预留导航。",
      },
      {
        id: "interest",
        title: "兴趣班记录",
        description: "记录兴趣班信息、课时消耗与上课明细",
        icon: "🎓",
        accent: "#8b5cf6",
        action: "interest-class",
        keywords: ["兴趣班", "课时", "课程"],
        badge: "新功能",
      },
    ],
  },
];

export const APP_INFO_ITEMS: AppInfoItem[] = [
  { label: "版本号", value: "1.0.310" },
  { label: "提交版本", value: "e6f8ba" },
  { label: "构建时间", value: "2026/03/18" },
  { label: "最后更新", value: "2026-03-18" },
  { label: "环境", value: "生产环境" },
];
